parameters:
    pim_catalog.entity.product_value.class: Pim\Bundle\ExtendedEeBundle\Model\ProductValue
    pimee_workflow.entity.published_product_value.class: Pim\Bundle\ExtendedEeBundle\Model\PublishedProductValue
