parameters:
    pim_catalog.comparator.attribute.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Updater\Comparator\TextCollectionComparator

services:
    pim_extended_attribute_type.comparator.attribute.text_collection:
        class: '%pim_catalog.comparator.attribute.text_collection.class%'
        arguments:
            - ['pim_catalog_text_collection']
        tags:
            - { name: pim_catalog.attribute.comparator }
