parameters:
    pim_filter.form.type.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\DataGrid\Form\Type\Filter\TextCollectionFilterType

services:
    pim_filter.form.type.text_collection:
        class: '%pim_filter.form.type.text_collection.class%'
        arguments:
            - '@translator'
        tags:
            - { name: form.type, alias: pim_type_text_collection_filter }
