parameters:
    pim_extended_attribute_type.validator.constraint_guesser.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Validator\ConstraintGuesser\TextCollectionGuesser

services:
    pim_extended_attribute_type.validator.constraint_guesser.text_collection:
        public: false
        class: '%pim_extended_attribute_type.validator.constraint_guesser.text_collection.class%'
        tags:
            - { name: pim_catalog.constraint_guesser.attribute }
