language: php

php: 7.1

git:
    depth: 5

cache:
    directories:
        - $HOME/.composer/cache

install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"
    - composer --prefer-dist --no-interaction install

script:
    - ./vendor/bin/phpspec run
