parameters:
    pim_extended_attribute_type.localization.presenter.string_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Localization\Presenter\TextCollectionPresenter

services:
    pim_extended_attribute_type.localization.presenter.string_collection:
        class: '%pim_extended_attribute_type.localization.presenter.string_collection.class%'
        tags:
            - { name: pim_catalog.localization.presenter, type: 'product_value' }
