parameters:
    pim_extended_attribute_type.completeness.checker.string_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Completeness\Checker\TextCollectionCompleteChecker

services:
    pim_extended_attribute_type.completeness.checker.string_collection:
        class: '%pim_extended_attribute_type.completeness.checker.string_collection.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }
