parameters:

services:
    pim_extended_attribute_type.comparator.attribute.string_collection:
        class: '%pim_catalog.comparator.attribute.options.class%'
        arguments:
            - ['pim_catalog_string_collection']
        tags:
            - { name: pim_catalog.attribute.comparator }
