parameters:
    pim_extended_attribute_type.comparator.product_range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Comparator\Attribute\RangeComparator

services:
    pim_extended_attribute_type.comparator.product_range:
        class: '%pim_extended_attribute_type.comparator.product_range.class%'
        tags:
            - { name: pim_catalog.attribute.comparator }

    pim_extended_attribute_type.comparator.attribute.scalar:
        class: '%pim_catalog.comparator.attribute.scalar.class%'
        arguments:
            - [ 'pim_extended_attribute_type_text_collection']
        tags:
            - { name: pim_catalog.attribute.comparator, priority: -128 }
