parameters:
    pim_catalog.comparator.attribute.string_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Updater\Comparator\StringCollectionComparator

services:
    pim_extended_attribute_type.comparator.attribute.string_collection:
        class: '%pim_catalog.comparator.attribute.string_collection.class%'
        arguments:
            - ['pim_catalog_string_collection']
        tags:
            - { name: pim_catalog.attribute.comparator }
