config:
    paths:
        pim-extended-attribute-type/text-collection-field: pimextendedattributetype/js/product/field/text-collection-field
        pim-extended-attribute-type/templates/product/field/text-collection: pimextendedattributetype/templates/product/field/text-collection.html
