config:
    paths:
        pim-extended-attribute-type/text-collection-field: pimextendedattributetype/js/product/field/text-collection-field
        pim-extended-attribute-type/templates/product/field/text-collection: pimextendedattributetype/templates/product/field/text-collection.html

    config:
        pim/form/common/attributes/create-button:
            attribute_icons:
                pim_catalog_text_collection: book
