parameters:

services:
    pim_extended_attribute_type.validator.constraint_guesser.string_collection:
        public: false
        class: '%pim_extended_attribute_type.validator.constraint_guesser.string_collection.class%'
        tags:
            - { name: pim_catalog.constraint_guesser.attribute }
