parameters:
#    pim_extended_attribute_type.presenter.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Presenter\RangePresenter

services:
#    pim_extended_attribute_type.presenter.range:
#        class: '%pim_extended_attribute_type.presenter.range.class%'
#        arguments:
#            - '@pim_extended_attribute_type.localization.presenter.range'
#            - '@pim_enrich.resolver.locale'
#        tags:
#            - { name: pimee_workflow.presenter }
