Pim\Bundle\ExtendedEeBundle\Model\PublishedProductValue:
    type: entity
    table: pimee_workflow_published_product_value
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        textCollection:
            type: json_array
            nullable: true
            column: value_text_collection
    indexes:
        value_idx:
            columns:
                - attribute_id
                - locale_code
                - scope_code
        varchar_idx:
            columns:
                - value_string
        integer_idx:
            columns:
                - value_integer
