parameters:
    pim_extended_attribute_type.text_collection_filter.class: Pim\Bundle\ExtendedAttributeTypeBundle\Filter\ProductValue\TextCollectionFilter

services:
    pim_extended_attribute_type.text_collection_filter:
        class: '%pim_extended_attribute_type.text_collection_filter.class%'
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_text_collection }
